spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23linlOgcmYqhgyBUO
            client-secret: 0ec817836872dc01898cd1e912b1c694542b813a
            scope: read:user,user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
